spring:
  application:
    name: mall-portal
  profiles:
    active: dev # default is development environment
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization # request header where JWT is stored
  secret: mall-portal-secret # secret used for JWT encryption/decryption
  expiration: 604800 # JWT expiration time (60*60*24*7)
  tokenHead: 'Bearer '  # prefix for the JWT token value

secure:
  ignored:
    urls: # security path whitelist
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /alipay/**

# Custom Redis keys
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # auth code expiration time (seconds)
    common: 86400 # 24 hours

mongo:
  insert:
    sqlEnable: true # controls whether to insert into MongoDB using DB data

# Message queue definitions
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue
